### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by rojvv** [dcdunkan/deno_gramjs#22]
We need to support browsers. For this, we might want to keep away from `std/node` as much as we can, since it has many Deno-only code, and we have already faced enough problems with it.

- [x] Reduce bundle size to work. (Done in #19.)
- [x] Stop depending on `std/node/crypto.ts`. (Done in #20.)
- [x] Stop depending on `std/node/fs.ts`. (Done in #23.)
- [x] Stop depending on `std/node/net.ts`. (Done in #24/#25.)
- [x] Replace w3cwebsocket with the already-implemented `WebSocket`. (Done in #26.)

**Comment by rojvv** [comment]
Our current problem is in generating the auth key. It is stuck here: https://github.com/grmjs/grm/blob/87751ebd313b1e3f62b73e322887934110d124f0/src/network/mtproto_plain_sender.ts#L31

**Comment by roj1512** [comment]
It seems like the problem is with `PromisedWebSockets`, and exists on Deno, too. Logs with debug:

```shell
[2022-11-20T14:14:43.997] [DEBUG] - [Connection attempt 0...] 
[2022-11-20T14:14:43.997] [DEBUG] - [Connecting] 
[2022-11-20T14:14:44.399] [DEBUG] - [Finished connecting] 
[2022-11-20T14:14:44.400] [DEBUG] - [Connection success!] 
[2022-11-20T14:14:44.400] [DEBUG] - [Already have an auth key ...] 
[2022-11-20T14:14:44.400] [DEBUG] - [Starting receive loop] 
[2022-11-20T14:14:44.401] [DEBUG] - [Receiving items from the network...] 
[2022-11-20T14:14:44.401] [DEBUG] - [Starting send loop] 
[2022-11-20T14:14:44.401] [DEBUG] - [Waiting for messages to send...false] 
[2022-11-20T14:14:44.402] [INFO] - [Connection to 149.154.167.51:80/TCPFull complete!] 
[2022-11-20T14:14:44.405] [INFO] - [Using LAYER 145 for initial connect] 
[2022-11-20T14:14:44.407] [DEBUG] - [Assigned msgId = 7168055107299921920 to InvokeWithLayer] 
[2022-11-20T14:14:44.408] [DEBUG] - [Encrypting 1 message(s) in 68 bytes for sending] 
[2022-11-20T14:14:44.410] [DEBUG] - [Encrypted messages put in a queue to be sent] 
[2022-11-20T14:14:44.410] [DEBUG] - [Waiting for messages to send...false] 
[2022-11-20T14:14:44.599] [INFO] - [The server closed the connection] 
[2022-11-20T14:14:44.600] [ERROR] - [Error: Not connected] 
[2022-11-20T14:14:44.600] [WARN] - [Connection closed while receiving data...] 
[2022-11-20T14:14:44.600] [INFO] - [Starting reconnect...] 
[2022-11-20T14:14:44.600] [DEBUG] - [Closing current connection...] 
[2022-11-20T14:14:44.601] [INFO] - [Connecting to 149.154.167.51:80/TCPFull using PromisedWebSocket] 
[2022-11-20T14:14:44.601] [DEBUG] - [Connection attempt 0...] 
[2022-11-20T14:14:44.601] [DEBUG] - [Connecting] 
[2022-11-20T14:14:45.009] [DEBUG] - [Finished connecting] 
[2022-11-20T14:14:45.009] [DEBUG] - [Connection success!] 
[2022-11-20T14:14:45.010] [DEBUG] - [Already have an auth key ...] 
[2022-11-20T14:14:45.010] [DEBUG] - [Starting receive loop] 
[2022-11-20T14:14:45.010] [DEBUG] - [Receiving items from the network...] 
[2022-11-20T14:14:45.010] [DEBUG] - [Starting send loop] 
[2022-11-20T14:14:45.010] [DEBUG] - [Waiting for messages to send...false] 
[2022-11-20T14:14:45.010] [INFO] - [Connection to 149.154.167.51:80/TCPFull complete!] 
WARNING the security module is not active
[2022-11-20T14:14:46.016] [DEBUG] - [Assigned msgId = 7168055114321856672 to InvokeWithLayer] 
[2022-11-20T14:14:46.016] [DEBUG] - [Encrypting 1 message(s) in 68 bytes for sending] 
[2022-11-20T14:14:46.019] [DEBUG] - [Encrypted messages put in a queue to be sent] 
[2022-11-20T14:14:46.019] [DEBUG] - [Waiting for messages to send...false] 
[2022-11-20T14:14:46.019] [DEBUG] - [Assigned msgId = 7168055114337856468 to users.GetUsers] 
[2022-11-20T14:14:46.019] [DEBUG] - [Encrypting 1 message(s) in 32 bytes for sending] 
[2022-11-20T14:14:46.021] [DEBUG] - [Encrypted messages put in a queue to be sent] 
[2022-11-20T14:14:46.021] [DEBUG] - [Waiting for messages to send...false] 
[2022-11-20T14:14:46.341] [INFO] - [The server closed the connection] 
[2022-11-20T14:14:46.341] [ERROR] - [Error: Not connected] 
[2022-11-20T14:14:46.341] [WARN] - [Connection closed while receiving data...] 
[2022-11-20T14:14:46.341] [INFO] - [Starting reconnect...] 
[2022-11-20T14:14:46.341] [DEBUG] - [Closing current connection...] 
[2022-11-20T14:14:46.342] [INFO] - [Connecting to 149.154.167.51:80/TCPFull using PromisedWebSocket] 
[2022-11-20T14:14:46.342] [DEBUG] - [Connection attempt 0...] 
[2022-11-20T14:14:46.342] [DEBUG] - [Connecting] 
[2022-11-20T14:14:46.750] [DEBUG] - [Finished connecting] 
[2022-11-20T14:14:46.750] [DEBUG] - [Connection success!] 
[2022-11-20T14:14:46.750] [DEBUG] - [Already have an auth key ...] 
[2022-11-20T14:14:46.750] [DEBUG] - [Starting receive loop] 
[2022-11-20T14:14:46.750] [DEBUG] - [Receiving items from the network...] 
[2022-11-20T14:14:46.750] [DEBUG] - [Starting send loop] 
[2022-11-20T14:14:46.750] [DEBUG] - [Waiting for messages to send...false] 
[2022-11-20T14:14:46.750] [INFO] - [Connection to 149.154.167.51:80/TCPFull complete!] 
WARNING the security module is not active
[2022-11-20T14:14:47.753] [DEBUG] - [Assigned msgId = 7168055121564823924 to InvokeWithLayer] 
[2022-11-20T14:14:47.753] [DEBUG] - [Assigned msgId = 7168055121568823632 to users.GetUsers] 
[2022-11-20T14:14:47.754] [DEBUG] - [Encrypting 2 message(s) in 124 bytes for sending] 
[2022-11-20T14:14:47.757] [DEBUG] - [Encrypted messages put in a queue to be sent] 
[2022-11-20T14:14:47.757] [DEBUG] - [Waiting for messages to send...false] 
[2022-11-20T14:14:47.757] [DEBUG] - [Assigned msgId = 7168055121584823428 to users.GetUsers] 
[2022-11-20T14:14:47.758] [DEBUG] - [Encrypting 1 message(s) in 32 bytes for sending] 
[2022-11-20T14:14:47.760] [DEBUG] - [Encrypted messages put in a queue to be sent] 
[2022-11-20T14:14:47.760] [DEBUG] - [Waiting for messages to send...false] 
[2022-11-20T14:14:47.979] [INFO] - [The server closed the connection] 
[2022-11-20T14:14:47.979] [ERROR] - [Error: Not connected] 
[2022-11-20T14:14:47.979] [WARN] - [Connection closed while receiving data...] 
[2022-11-20T14:14:47.979] [INFO] - [Starting reconnect...] 
[2022-11-20T14:14:47.979] [DEBUG] - [Closing current connection...] 
[2022-11-20T14:14:47.980] [INFO] - [Connecting to 149.154.167.51:80/TCPFull using PromisedWebSocket] 
[2022-11-20T14:14:47.980] [DEBUG] - [Connection attempt 0...] 
[2022-11-20T14:14:47.980] [DEBUG] - [Connecting] 
[2022-11-20T14:14:48.285] [DEBUG] - [Finished connecting] 
[2022-11-20T14:14:48.286] [DEBUG] - [Connection success!] 
[2022-11-20T14:14:48.286] [DEBUG] - [Already have an auth key ...] 
[2022-11-20T14:14:48.286] [DEBUG] - [Starting receive loop] 
[2022-11-20T14:14:48.286] [DEBUG] - [Receiving items from the network...] 
[2022-11-20T14:14:48.286] [DEBUG] - [Starting send loop] 
[2022-11-20T14:14:48.286] [DEBUG] - [Waiting for messages to send...false] 
[2022-11-20T14:14:48.286] [INFO] - [Connection to 149.154.167.51:80/TCPFull complete!] 
WARNING the security module is not active
[2022-11-20T14:14:49.289] [DEBUG] - [Assigned msgId = 7168055128298758568 to InvokeWithLayer] 
[2022-11-20T14:14:49.289] [DEBUG] - [Assigned msgId = 7168055128302758280 to users.GetUsers] 
[2022-11-20T14:14:49.290] [DEBUG] - [Assigned msgId = 7168055128302758284 to users.GetUsers] 
[2022-11-20T14:14:49.291] [DEBUG] - [Assigned msgId = 7168055128306757988 to users.GetUsers] 
[2022-11-20T14:14:49.291] [DEBUG] - [Encrypting 4 message(s) in 188 bytes for sending] 
[2022-11-20T14:14:49.293] [DEBUG] - [Encrypted messages put in a queue to be sent] 
[2022-11-20T14:14:49.293] [DEBUG] - [Waiting for messages to send...false]
```
